

model: 
  image_size: 512
  pretrained_model_name_or_path: 'google/vit-base-patch16-224'
  freeze_encoder_weights: true
  num_classes: 2
  id2label: {
              0: 'cat',
              1: 'dog'
  }
  checkpoint: null

data: 
  root: /home/paulw/data/dogs-vs-cats/data
  num_workers: 8
  batch_size: 8
  image_size: 512
  use_augmentations: true

training: 
  max_epochs: 1
  logdir: ~/logs
  mode: train
