

model: 
  image_size: 224
  pretrained_model_name_or_path: 'google/vit-base-patch16-224'
  freeze_encoder_weights: true
  num_classes: 2
  id2label: {
              0: 'cat',
              1: 'dog'
  }

data: 
  root: /home/paulw/data/dogs-vs-cats/data
  num_workers: 8
  batch_size: 128
  image_size: 224
  use_augmentations: true

training: 
  mode: train
  max_epochs: 1
  logdir: ~/lightning_logs
  ckpt_path: null #~/lightning_logs/default/version_0/checkpoints/epoch=0-step=156.ckpt
