

model: 
  image_size: 384
  pretrained_model_name_or_path: 'google/vit-large-patch16-384'
  freeze_encoder_weights: true

data: 
  num_workers: 8
  batch_size: 32
  root: null
  image_size: 384  
  use_augmentations: false

training: 
  max_epochs: 1
  logdir: null

