
dataset:
  root_dir: '/home/paulw/data/train'
  use_augmentations: true

model:
  name: 'resnet_18'
  method: 'store' # alternatively, factory
  config: # if using factory, specify model hyper parameters.

optimizer:
  learning_rate: 1e-3

training:
  epochs: 100
  batch_size: 256
  load_from_latest_ckpt: false # epoch from which to load the model

expt_dir: '/home/paulw/catformer/test_expt'
